package avramenko.view;

public enum Activities {
    SHOW_MAIN_MENU,
    GENERATE_CAR_LIST,
    CREATE_CAR_LIST,
    TXT_FILE_READ,
    JSON_FILE_READ,
    SERIALIZATION_FILE_READ,
    TXT_FILE_WRITE,
    JSON_FILE_WRITE,
    SERIALIZATION_FILE_WRITE,
    SHOW_SAVE_MENU,
    SHOW_SUBMENU,
    GET_BRAND,
    GET_MODEL,
    GET_YEAR,
    EXIT
}
